### ISSUE TITLE
fix Mopub Adapter clickable childView only

### ISSUE THREAD

**Issue by artemkutukov** [myTargetSDK/mytarget-android#1]
Могли бы вы добавить эти исправления в SDK.
[Git change ](http://joxi.ru/Q2Kennku9oX9Yr?d=1)
https://gist.github.com/artemkutukov/6c979701693dcadc25b9431288ebb157

[Git change MyTargetStaticNativeAd.class](http://joxi.ru/KAgYKKRsgxe4Dm?d=1)
https://gist.github.com/artemkutukov/eff1ec84c7e6b3f4661b3b26ffea1c42

**Comment by lostillusion** [comment]
Артем, класс NativeClickHandler - это класс Mopub SDK, а не наш, используем мы его на основании их гайдов - https://github.com/mopub/mopub-android-sdk/wiki/Custom-Events (п.5).
Если вы считаете, что в приведенном вами методе в этом классе, стоит поменять местами строки или как-то ещё изменить его функционал, то вам стоит написать об этом в Mopub. Мы лишь используем предоставляемый ими код для реализации медиации.

**Comment by artemkutukov** [comment]
Да, но вы можете создать свой класс и добавить его в обратку. Или же сделать параметр BOOL для выбора дефолтного класса или написанного Вами. Не вижу проблем в этом. 

Дополнительно открою тикет в MoPub.

**Comment by lostillusion** [comment]
У нас нет информации о каких-либо проблемах с этим у кого-то ещё, хотя медиацию через Mopub используют многие. Если Mopub подтвердит ошибку - мы радостью поменяем.

**Comment by artemkutukov** [comment]
Учитывая, что все уходят от мисс кликов при показе рекламы (тот же Facebook Audience Network), не думаю, что Вас должно устраивать это =) Ну если всем нравится, пускай будет так. Спасибо.

**Comment by lostillusion** [comment]
Так используйте нас напрямую, у нас есть все методы для защиты от мисскликов, зачем вам Mopub?;)
