### ISSUE TITLE
Краш на Android 4.1-4.4

### ISSUE THREAD

**Issue by MoNTE48** [myTargetSDK/mytarget-android#12]
```java
java.lang.NoClassDefFoundError: com.my.target.ae
        at g.a.a.a.a.G(outline:-1)
        at com.my.target.dd.h(Unknown:-1)
        at com.my.target.dd.c(Unknown:-1)
        at com.my.target.dd.d(Unknown:-1)
        at com.my.target.dc.g(Unknown:-1)
        at com.my.target.ij$2.run(Unknown:-1)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)
```

Ничего подробнее Bugsnag не предоставил, к сожалению. Более 3000 крашей и строго на Android 4.1-4.4.

**Comment by alexskobozev** [comment]
Есть возможность узнать, какая версия СДК в приложении?

**Comment by MoNTE48** [comment]
Самая последняя. 
Файлы для деобфускации автоматически выгружены в Bugsnag. Я вижу нормальный трейс для каждой ошибки кроме того что связано с вашим SDK. Для уточнения: использую Appodeal медиацию. Вначале стояла версия поставляемая с их SDK. Потом ради интереса принудительно указал последнюю версию вашего SDK - не изменилось ничего.

**Comment by alexskobozev** [comment]
Спасибо, важное замечание, посмотрим что там с Appodeal

**Comment by alexskobozev** [comment]
@MoNTE48 какие рекламные форматы у вас используются?

**Comment by MoNTE48** [comment]
```java
private static final int adTypes = Appodeal.INTERSTITIAL | Appodeal.REWARDED_VIDEO;
Appodeal.initialize(activity, BuildConfig.apdAppKey, adTypes, consent);
```

**Comment by alexskobozev** [comment]
@MoNTE48 Можете скинуть apk или ссылку на плеймаркет?

**Comment by MoNTE48** [comment]
@alexskobozev https://play.google.com/store/apps/details?id=com.multicraft.game

**Comment by alexskobozev** [comment]
Спасибо. Поковырялся в апк, декомпилятор говорит, что каким-то образом вызов нашего класса завёрнут в какой-то левый метод, который делает только конкатенацию строк. Метода этого в реальности скорее всего нет, это декомпилятор попытался так построить оптимизацию.  Баг возникает в android 4.1-4.4, скорее всего это баг связанный с Multidex и оптимизацией, наподобие этого https://issuetracker.google.com/issues/131100011 Решение вижу в добавлении 
`-keep class com.my.target.common.** { *; }` 
в proguard-файл приложения чтобы исключить проблемы с минимизацией. Наше СДК само по себе минимизировано, так что размер apk увеличиться не должен.
Надеюсь поможет, если же нет, прошу переоткрыть ишью

**Comment by MoNTE48** [comment]
К сожалению ни 
`-keep class com.my.target.common.** { *; }`
ни даже более глобальное
`-keep class com.my.target.** { *; }`
проблему не решили...

**Comment by alexskobozev** [comment]
К сожалению, мы пока не можем воспроизвести проблему. Так как у нас нет проблем с этими форматами на чистом myTarget, скорее всего проблема с медиацией Appodeal и лучше обратиться к ним. Может конфликт с другими сетями. У вас какие рекламные сети/модули медиации установлены в приложении?

**Comment by MoNTE48** [comment]
```
	googleImplementation 'com.google.android.gms:play-services-ads:19.7.0'
	googleImplementation 'com.google.android.gms:play-services-location:17.1.0'
	implementation 'com.appodeal.ads.sdk:core:2.8.1'
	googleImplementation 'com.appodeal.ads.sdk.networks:adcolony:2.8.1.8'
	googleImplementation 'com.adcolony:sdk:4.4.0' // use latest AdColony SDK
	googleImplementation 'com.appodeal.ads.sdk.networks:applovin:2.8.1.9'
	googleImplementation 'com.applovin:applovin-sdk:9.15.1' // use latest AppLovin SDK
	googleImplementation('com.appodeal.ads.sdk.networks:bidmachine:2.8.1.4') {
		// bye-bye Mark...
		exclude group: 'com.facebook.android', module: 'audience-network-sdk'
		exclude group: 'io.bidmachine', module: 'ads.networks.facebook'
	}
	googleImplementation 'com.appodeal.ads.sdk.networks:my_target:2.8.1.8'
	googleImplementation 'com.my.target:mytarget-sdk:5.11.10' // use latest myTarget SDK
	googleImplementation 'com.appodeal.ads.sdk.networks:ogury:2.8.1.6'
	googleImplementation 'com.appodeal.ads.sdk.networks:unity_ads:2.8.1.7'
	googleImplementation 'com.unity3d.ads:unity-ads:3.6.0' // use latest UnityAds SDK
```
