### ISSUE TITLE
ImageData cache bitmap lose effectiveness!!!

### ISSUE THREAD

**Issue by whistlexie** [myTargetSDK/mytarget-android#17]
because ImageData class didn`t override hash and equel method,so we can`t  find the cache bitmap by a ImageData object from LinkedHashMap.
Like this.manay the same picture are store in the memory.

![image](https://user-images.githubusercontent.com/10007354/186851328-d51bfac1-3a41-49aa-aa08-80c94997b082.png)

//miss hash and equeal method.
public final class ImageData extends u1<Bitmap> {
    private static final int MIN_CACHE_SIZE = 5242880;
    private static final int DEFAULT_CACHE_SIZE = 31457280;
    @NonNull
    private static volatile LruCache<ImageData, Bitmap> memcache = new ImageData.BitmapCache(31457280);
    private volatile boolean useCache;

    @AnyThread
    public static void setCacheSize(int sizeInBytes) {
        if (sizeInBytes < 5242880) {
            e0.a("setting cache size ignored: size should be >=5242880");
        } else {
            if (VERSION.SDK_INT >= 21) {
                memcache.resize(sizeInBytes);
            } else {
                memcache = new ImageData.BitmapCache(sizeInBytes);
            }

        }
    }

    @AnyThread
    public static void clearCache() {
        memcache.evictAll();
    }

    @NonNull
    public static ImageData newImageData(@NonNull String url) {
        return new ImageData(url);
    }

    @NonNull
    public static ImageData newImageData(@NonNull String url, int width, int height) {
        return new ImageData(url, width, height);
    }

    private ImageData(@NonNull String url) {
        super(url);
    }

    private ImageData(@NonNull String url, int width, int height) {
        super(url);
        super.width = width;
        super.height = height;
    }

    public boolean isUseCache() {
        return this.useCache;
    }

    @Nullable
    public Bitmap getBitmap() {
        return this.getData();
    }

    public void setBitmap(@Nullable Bitmap bitmap) {
        this.setData(bitmap);
    }

    @Nullable
    public Bitmap getData() {
        return this.useCache ? (Bitmap)memcache.get(this) : (Bitmap)super.getData();
    }

    public void setData(@Nullable Bitmap data) {
        if (this.useCache) {
            if (data == null) {
                memcache.remove(this);
            } else {
                memcache.put(this, data);
            }
        } else {
            super.setData(data);
        }

    }

    public void useCache(boolean use) {
        if (use != this.useCache) {
            this.useCache = use;
            if (use) {
                Bitmap use1;
                if ((use1 = (Bitmap)super.getData()) != null) {
                    super.setData((Object)null);
                    memcache.put(this, use1);
                }
            } else {
                super.setData((Bitmap)memcache.remove(this));
            }

        }
    }

    @NonNull
    public String toString() {
        return "ImageData{url='" + super.url + '\'' + ", width=" + super.width + ", height=" + super.height + ", bitmap=" + this.getData() + '}';
    }

    public static class BitmapCache extends LruCache<ImageData, Bitmap> {
        public BitmapCache(int maxSize) {
            super(maxSize);
        }

        public int sizeOf(ImageData key, Bitmap value) {
            return VERSION.SDK_INT >= 19 ? value.getAllocationByteCount() : value.getByteCount();
        }
    }
}

**Comment by baoti** [comment]
@alexskobozev Do you know of any fix plans for this?

**Comment by alexskobozev** [comment]
@baoti I don't know, sorry

**Comment by altk** [comment]
Thank you for submitting the issue.
We have put it to our backlog.

**Comment by skandakov** [comment]
Fixed in 5.16.5
