### ISSUE TITLE
Возможность закрыть рекламу на Android TV (D-Pad)

### ISSUE THREAD

**Issue by kirkaDev** [myTargetSDK/mytarget-android#19]
Добрый день.

Я столкнулся с тем, что при запуске на Android TV рекламы RewardedAd нет возможности закрыть рекламу (нажать крестик), а учитывая то, что переход по бекстеку блокируется, приложение превращается в вирус.

Предлагаю два варианта:
1. Для view крестика вызывать например метод requestFocus(), тогда при использовании D-Pad можно будет закрывать рекламу.
В ImaSDK от Google когда кнопка "Пропустить рекламу" становится активной, то именно так и происходит.
Еще у них видео с рекламой обводится рамкой (выделяется как фокус), если нажать на кнопку "Ок" на пульте, то происходит переход по рекламе.
После просмотра реклама автоматически закрывается. Возможно, я попросту не нашел как это делается в myTarget.

2. Добавить возможность посредством API выполнять dismiss для рекламы (чтобы вызывать его, после получения события onReward() листенера RewardedAd.RewardedAdListener)

P.S.: Если на данный момент нет возможности закрытия рекламы на TV, то вы теряете часть рынка.

**Comment by altk** [comment]
Метод dismiss() уже есть в API.

**Comment by kirkaDev** [comment]
> Метод dismiss() уже есть в API.

Я такого не нашел.
Видел только коллбек onDismiss, но он вызывается при нажатии на кнопку "Закрыть".

Я сейчас вызываю метод destroy() у объекта RewardedAd, ExoPlayer после этого запускает видео, но я не уверен, что верно поступаю.

Я вижу публичные методы у RewardedAd.engine, такие как d(), a(), c(), которые можно вызывать, но, к сожалению, они обфусцированы, поэтому сложно понять, для чего они предназначены. Интересно, это так задумано или названия этих методов случайно попали под обфускацию?

**Comment by kirkaDev** [comment]
А всё, вижу, там же и метод RewardedAd.engine.dismiss(), благодарю.

**Comment by aserrr** [comment]
> Я вижу публичные методы у RewardedAd.engine, такие как d(), a(), c(), которые можно вызывать, но, к сожалению, они обфусцированы, поэтому сложно понять, для чего они предназначены. Интересно, это так задумано или названия этих методов случайно попали под обфускацию?

Очевидно же, что это приватные методы.
А вызывать следует публичный rewardedAd.dismiss()
[пример](https://github.com/myTargetSDK/mytarget-android/blob/master/myTargetDemo/app/src/main/java/com/my/targetDemoApp/helpers/RewardedHelper.kt#L49)

**Comment by kirkaDev** [comment]
> 

ок, я нашел то что искал, спасибо.

А по поводу методов, это методы интерфейса, которые я могу вызвать. Как я смог бы приватный метод вызвать?
Просто, вдруг он может быть мне полезен, а я не знаю что он делает?
