### ISSUE TITLE
MoPub onImpression() не срабатывает

### ISSUE THREAD

**Issue by UnateD** [myTargetSDK/mytarget-android#6]
Добрый день! Используем медиацию MoPub в проекте. Имеется реализация для myTarget native. После показа банера 
`public void onShow(@NonNull NativeAd ad)`
триггерим `notifyAdImpressed()`
однако callback в ImpressionListener MoPub не прилетает. 
Что-то делаем не так? Есть какие-то особые условия вызова notifyAdImpressed ?

**Comment by alexskobozev** [comment]
Здравствуйте, подскажите пожалуйста, какая именно реализация для медиации имеется в виду? Если вы вызываете мопабовский notifyAdImpressed() после показа, то мопаб сам вызывает колбэк, мы никак не влияем на этот процесс. 
Например, реализация мопаба https://github.com/mopub/mopub-android-sdk/blob/master/mopub-sample/src/main/java/com/mopub/simpleadsdemo/NativeManualFragment.java 
Работает отлично с нашими адаптерами, и колбэк onImpression вызывается.

**Comment by UnateD** [comment]
Используется данный вариант:
https://github.com/myTargetSDK/mytarget-android/tree/master/mediation/mopub/com
От нас из собственного только renderer класс для регистрации в MoPub при инициализации.  Проблема в том, что не срабатывает не `onImpression` в слушателе, а нет реакции класса `ImpressionListener` конкретно в методе `public void onImpression(@NonNull String adUnitId, @Nullable ImpressionData impressionData)` , предоставляющем информацию о произошедшем показе.

**Comment by alexskobozev** [comment]
Не могу ничего точно сказать без примера кода. Пока выглядит как проблема реализации именно мопабовской части

**Comment by UnateD** [comment]
Собственного у нас лишь renderer, который реализует в себе загрузку данных из банера в view. В остальном - код по ссылке выше. Баннер отображается, показы считаются. Но есть проблема с отсутствием impression data в callback'е (в случаях с остальными провайдерами ситуация не повторяется, насколько мы видим), плюс у myTarget при реализации через MoPub медиацию низкий ctr. Возможно это как-то связано или мы не знаем каких-то правил для реализации?
