### ISSUE TITLE
Ошибка в MyTargetCustomEventNative

### ISSUE THREAD

**Issue by kutukoff** [myTargetSDK/mytarget-android#9]
Добрый день,

вижу, что в классе `MyTargetCustomEventNative.java` строка 43:
`MopubCustomParamsUtils.fillCustomParams(nativeAd.getCustomParams(), extras);`
<img width="700" alt="image" src="https://user-images.githubusercontent.com/9209799/102687387-66a8d400-41f7-11eb-9f6e-c7fe28b074af.png">
метод собирает только extras с сервера Mopub, а параметры localExtras (с vk_id, age, gender, которые генерируются с клиента) не передается в com.my.target.common.CustomParams.

Могли бы исправить?
Спасибо.

**Comment by alexskobozev** [comment]
Добрый день, напишите, пожалуйста, пример кода, как вы добавляете эти параметры (vk_id, age, gender) в нативную рекламу MoPub

**Comment by kutukoff** [comment]
Добрый день, 

вот так выглядит создание мапы:
```
private fun getParametersKeywordsLocal(context: Context): Map<String, Any> {
        val objects: MutableMap<String, Any> = HashMap()
        objects[MopubCustomParamsUtils.EXTRA_AGE] = "25"
        objects[MopubCustomParamsUtils.EXTRA_GENDER] = "1"
        objects[MopubCustomParamsUtils.EXTRA_VKID] = "99999999"

        return objects
    }
```

Через `moPubNative.setLocalExtras`, вот происходит создание рендера:
```
        val adRendererRegistry = AdRendererRegistry()
        adRendererRegistry.registerAdRenderer(MyTargetAdRenderer(targetBinder))
        adRendererRegistry.registerAdRenderer(MoPubStaticNativeAdRenderer(viewBinder))

        val moPubNative = MoPubNative(context, getMoPubNativeId(), adRendererRegistry, listener)
        moPubNative.setLocalExtras(getParametersKeywordsLocal(context))

        //Specify which native assets you want to use in your ad.
        val assetsSet = EnumSet.of(
            NativeAdAsset.TITLE,
            NativeAdAsset.TEXT,
            NativeAdAsset.MAIN_IMAGE,
            NativeAdAsset.ICON_IMAGE,
            NativeAdAsset.CALL_TO_ACTION_TEXT
        )
        moPubNative.makeRequest(getRequestParameters(context, assetsSet))
```

В методе `MyTargetCustomEventNative.loadNativeAd` функция `MopubCustomParamsUtils.fillCustomParams` достает эти параметры из extras, а не localExtra.

**Comment by kutukoff** [comment]
@alexskobozev есть апдеты по реквесту ?

**Comment by alexskobozev** [comment]
тестируется

**Comment by kutukoff** [comment]
@alexskobozev Спасибо за исправление!
